sudo: required

language: node_js

services:
  - docker

cache:
  directories:
    - node_modules

notifications:
  email:
    - yadav.21@osu.edu
    - henderson.molly4@gmail.com

before_install:
  - docker build -t mofb-api .

script:
  - npm run build
