swagger: '2.0'
info:
  title: 'Mid Ohio Food Bank RESTful API'
  description: ''
  version: '0.0.1'
  contact:
    name: 'Report an Issue'
    url: 'https://github.com/SCODEMeetup/mofb-api/issues'
servers:
  - url: 'http://localhost:3000'
    description: 'running locally'
  - url: 'https://mofb-api.appspot.com'
    description: 'Production server'  
basePath: '/'
paths:
  /pantries:
    get:
      tags:
        - 'Pantries'
      summary: 'returns a list of pantries'
      parameters:
        - name: limit
          in: query
          required: false
          description: 'The maximum number of results returned'
          schema:
            type: integer
            format: int64
            minimum: 1
            default: 100
        - name: pageNumber
          in: query
          required: false
          description: 'The page number of the data to be returned'
          schema:
            type: integer
            format: int64
            minimum: 1
            default: 1
      responses: 
        '200':
          description: 'Successfully queries the smart city datasets and returns the results'
  /pantries/{zipCode}:
    get:
      tags:
        - 'Pantries'
      summary: 'returns a list of pantries within that zipcode'
      parameters:
        - name: zipCode
          in: path
          required: true
          description: 'The zip code for food pantry search area'
          schemea:
            type: integer
            format: int64
        - name: limit
          in: query
          required: false
          description: 'The maximum number of results returned'
          schema:
            type: integer
            format: int64
            minimum: 1
            default: 100
        - name: pageNumber
          in: query
          required: false
          description: 'The page number of the data to be returned'
          schema:
            type: integer
            format: int64
            minimum: 1
            default: 1
      responses: 
        '200':
          description: 'Successfully queries the smart city datasets and returns the results'
externalDocs:
  description: 'Find out more about the API'
  url: 'https://github.com/SCODEMeetup/mofb-api'
